 import React from 'react';
import AboutUsNav from './AboutUsNav';

class AboutUs extends React.Component {
   
    render() {
        return (
            <div id='about_us'>
            {console.log(this.props)}

            {console.log(this.props.user)}
                <AboutUsNav user={this.props.user}/>
                <div className='container-fluid'>
                    <div className='row justify-content-center' style={{padding:'30px 0'}}>
                        <h2> About Us</h2>
                    </div>
                    <div className='row'>
                    
                    <div className='row'>
                        <h4> Why does Tably exist? </h4>
                    </div>
                    <div className='row'>
                        <div className='col-md-8'>
                            <span>
                                Tably was created as a way for charities and non-profits to fundraise
                                and create recurring revenue. It also allows donors the opportunity to
                                give money to the charities and non-profits even when they do not have the
                                    financial means to give. </span>
                        </div>
                    </div>
                    <div className='row'>
                        <h4> How does Tably work? </h4>
                    </div>
                    <div className='row'>
                        <div className='col-md-8'>
                            <span>
                                Tably helps by changing the new tab or window background generated by chrome.
                                Instead of your typical background, you'll see a modified background with ads on the
                                bottom and the side. Every time you create a new tab or window, Tably generates money
                                for the ads shown.
                                <br/> <br/>
                                There are two options for Tably members to choose the groups receiving donations.
                                The first doesn't require an account. Simply download the chrome extension and start using 
                                it! All of the revenue generated will be donated to the that month's Charity of the Month. 
                                The second requires an account. Once created, you will be able to choose which charity you would
                                like for your donations to go to. Simple as that. 
                            </span>
                        </div>
                    </div>
                    <div className='row'>
                        <h4> Wait, how do I know that the money is being donated? </h4>
                    </div>
                    <div className='row'>
                        <div className='col-md-8'>
                            <span>
                                At the time, I will be directly donating the money received from Google and posting the relative 
                                documents here when I receive them as proof of the donations. I'm
                                currently working to have Tably classified as a 501(c) organization. This will serve two 
                                purposes, the first being a tax deduction on the revenue received from Google. The second
                                would be to get audited in order to show third party audits of the donations made.
                             
                            </span>
                        </div>
                    </div>
                    <div className='row'>
                        <h4> How much of my money will be donated? </h4>
                    </div>
                    <div className='row'>
                        <div className='col-md-8'>
                            <span>
                                We're still at the beginning stages here so we don't have solid numbers as of yet.
                                However, the goal is to donate a minimum 50% of gross revenue to all of the organizations.
                                At the end of every quarter, I'll be posting a breakdown of the use of gross revenue. 

                            </span>
                        </div>
                    </div>
                    </div>

                </div>
            </div>
        )
    }
}
export default AboutUs